// import "./Member.css";
import Head from "next/head";
import React, { useState } from "react";
import SearchMember from "../../components/SearchMember";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import styles from "../../styles/Home.module.css";
const Member = () => {
  const [searchMember, setSearchMember] = useState("");
  const takeSearchMember = (val) => {
    setSearchMember(val);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.allSection}>
        <div>
          <Header />
          <Footer />
        </div>
        <main>
          <h2>Member</h2>
          <section>
            <SearchMember takeSearchMember={takeSearchMember} />
          </section>
        </main>
      </div>
    </>
  );
};

export default Member;
